table cust
	lineageTag: e91c1517-81cb-41c0-81e3-904e28f164eb

	measure 'Tổng số khách hàng' = COUNTROWS(cust)
		formatString: #,0
		lineageTag: 3445b94c-44b4-4435-8d98-f0ab2fdc35e9

	measure '% Tổng khách hàng' = DIVIDE([Tổng số khách hàng], CALCULATE([Tổng số khách hàng], ALL(cust[Phân khúc])))
		formatString: 0%
		lineageTag: 066ed70e-7a0c-49ab-b0dd-ca95e71c4911

	column 'Mã KH'
		dataType: int64
		formatString: 0
		lineageTag: e553dbff-49a9-4f42-a6ea-87d5893b55fe
		summarizeBy: none
		sourceColumn: Mã KH

		annotation SummarizationSetBy = Automatic

	column 'Phân khúc'
		dataType: string
		lineageTag: a4e44541-daa1-427d-a073-b4c461350b5c
		summarizeBy: none
		sourceColumn: Phân khúc

		annotation SummarizationSetBy = Automatic

	column 'Tỉnh thành'
		dataType: string
		lineageTag: dd23b9c9-323b-496e-9434-66eb12b5da1f
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: Tỉnh thành

		annotation SummarizationSetBy = Automatic

	column 'Quốc gia'
		dataType: string
		lineageTag: 67d30708-b187-4aba-896d-22633a357a16
		summarizeBy: none
		sourceColumn: Custom

		annotation SummarizationSetBy = Automatic

	column 'Vĩ độ' =
			SWITCH(cust[Tỉnh thành],
			"HA NOI", 21.0285,
			"HO CHI MINH", 10.8231,
			"DONG NAI", 10.9574,
			"HAI PHONG", 20.8449,
			"NGHE AN", 18.6733,
			"BINH DINH", 13.7757,
			"CAN THO", 10.0452,
			"THAI NGUYEN", 21.5942,
			"HAI DUONG", 20.9373,
			"VUNG TAU", 10.4114,
			"LONG AN", 10.5359,
			"BAC NINH", 21.1861,
			"GIA LAI", 13.9833,
			"VINH PHUC", 21.3089,
			"BINH THUAN", 10.9289,
			"DA NANG", 16.0544,
			"THANH HOA", 19.8067,
			"HA TINH", 18.3428,
			"PHU THO", 21.3227,
			"QUANG NINH", 20.9599,
			"NHA TRANG", 12.2388,
			"THUA THIEN HUE", 16.4637,
			"NAM DINH", 20.4341,
			"HOA BINH", 20.8171,
			"QUANG NAM", 15.5736,
			"BAC GIANG", 21.2731,
			"AN GIANG", 10.3860,
			"THAI BINH", 20.4463,
			"KIEN GIANG", 10.0125,
			"DONG THAP", 10.4938,
			"QUANG BINH", 17.4689,
			"VINH LONG", 10.2397,
			"BINH DUONG", 10.9804,
			"QUANG TRI", 16.8163,
			"DA LAT", 11.9404,
			"TIEN GIANG", 10.3600,
			"DAKLAK", 12.6667,
			"CA MAU", 9.1769,
			"Lang son", 21.8537,
			"HA NAM", 20.5417,
			"Hung yen", 20.6464,
			BLANK())
		dataType: double
		formatString: 0.0000
		lineageTag: de676936-73ac-45d6-8f55-96b478ce31c2
		summarizeBy: none

	column 'Kinh độ' =
			SWITCH(cust[Tỉnh thành],
			"HA NOI", 105.8542,
			"HO CHI MINH", 106.6297,
			"DONG NAI", 106.8426,
			"HAI PHONG", 106.6881,
			"NGHE AN", 105.6922,
			"BINH DINH", 109.2219,
			"CAN THO", 105.7469,
			"THAI NGUYEN", 105.8480,
			"HAI DUONG", 106.3145,
			"VUNG TAU", 107.1362,
			"LONG AN", 106.4139,
			"BAC NINH", 106.0763,
			"GIA LAI", 108.0000,
			"VINH PHUC", 105.6049,
			"BINH THUAN", 108.1022,
			"DA NANG", 108.2022,
			"THANH HOA", 105.7852,
			"HA TINH", 105.9057,
			"PHU THO", 105.4020,
			"QUANG NINH", 107.0432,
			"NHA TRANG", 109.1967,
			"THUA THIEN HUE", 107.5909,
			"NAM DINH", 106.1675,
			"HOA BINH", 105.3376,
			"QUANG NAM", 108.4740,
			"BAC GIANG", 106.1946,
			"AN GIANG", 105.4351,
			"THAI BINH", 106.3365,
			"KIEN GIANG", 105.0808,
			"DONG THAP", 105.6881,
			"QUANG BINH", 106.6222,
			"VINH LONG", 105.9722,
			"BINH DUONG", 106.6519,
			"QUANG TRI", 107.1005,
			"DA LAT", 108.4583,
			"TIEN GIANG", 106.3600,
			"DAKLAK", 108.0500,
			"CA MAU", 105.1524,
			"Lang son", 106.7610,
			"HA NAM", 105.9139,
			"Hung yen", 106.0512,
			BLANK())
		dataType: double
		formatString: 0.0000
		lineageTag: 1de381aa-57eb-4a01-98d1-4da2e7af72d7
		summarizeBy: none

	hierarchy 'Địa lý'
		lineageTag: 1b9ad1cc-a6eb-4d9a-9789-bafbd2081961

		level 'Quốc gia'
			lineageTag: d7d1e5a6-22a9-49e8-a54e-32889e462084
			column: 'Quốc gia'

		level 'Tỉnh thành'
			lineageTag: b22532ed-ee85-44fd-9bce-4977043caa5d
			column: 'Tỉnh thành'

	partition cust = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("D:\Data Self Learning\Tran Hoang Long _ Data Analyst Course\Data Analyst\Bank Customer Segmentation\Data\cust.csv"),[Delimiter=",", Columns=3, QuoteStyle=QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"customer_id", Int64.Type}, {"segment", type text}, {"province_city", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed column type",{{"customer_id", "Mã KH"}, {"segment", "Phân khúc"}, {"province_city", "Tỉnh thành"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Custom", each "Việt Nam")
				in
				    #"Added Custom"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

